// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqeWcBQYwldI2S5uJgIpMVsxIj4_GZ3gM',
    appId: '1:435042458714:web:41d11c5143c9d5efdc0c63',
    messagingSenderId: '435042458714',
    projectId: 'girisuygulamasi-283b8',
    authDomain: 'girisuygulamasi-283b8.firebaseapp.com',
    storageBucket: 'girisuygulamasi-283b8.appspot.com',
    measurementId: 'G-YRC346RBZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuvWJhi3BIE6L7IqzGj7e-ZIMHcj5VfEQ',
    appId: '1:435042458714:android:7162a36a8650c4dfdc0c63',
    messagingSenderId: '435042458714',
    projectId: 'girisuygulamasi-283b8',
    storageBucket: 'girisuygulamasi-283b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQGltoM6oGJmmZtjExlRaX6pAwHS7JlgU',
    appId: '1:435042458714:ios:842381bdd01ce1cadc0c63',
    messagingSenderId: '435042458714',
    projectId: 'girisuygulamasi-283b8',
    storageBucket: 'girisuygulamasi-283b8.appspot.com',
    iosBundleId: 'com.example.girisyapbackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQGltoM6oGJmmZtjExlRaX6pAwHS7JlgU',
    appId: '1:435042458714:ios:842381bdd01ce1cadc0c63',
    messagingSenderId: '435042458714',
    projectId: 'girisuygulamasi-283b8',
    storageBucket: 'girisuygulamasi-283b8.appspot.com',
    iosBundleId: 'com.example.girisyapbackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqeWcBQYwldI2S5uJgIpMVsxIj4_GZ3gM',
    appId: '1:435042458714:web:294705da70504366dc0c63',
    messagingSenderId: '435042458714',
    projectId: 'girisuygulamasi-283b8',
    authDomain: 'girisuygulamasi-283b8.firebaseapp.com',
    storageBucket: 'girisuygulamasi-283b8.appspot.com',
    measurementId: 'G-QVXBFW3YGD',
  );
}
